"""empty message

Revision ID: 20b8b13ac2ce
Revises: ba64c958310f
Create Date: 2019-07-31 21:46:51.675036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b8b13ac2ce'
down_revision = 'ba64c958310f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_pass_changes_ibfk_1', 'history_pass_changes', type_='foreignkey')
    op.create_foreign_key(None, 'history_pass_changes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_pass_changes', type_='foreignkey')
    op.create_foreign_key('history_pass_changes_ibfk_1', 'history_pass_changes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
