"""empty message

Revision ID: 5a9a1ad96a32
Revises: 705426ff6cab
Create Date: 2019-07-25 09:50:07.587858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a9a1ad96a32'
down_revision = '705426ff6cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_pass_changes', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_pass_changes', sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
